### ISSUE TITLE
name is_prime is not defined

### ISSUE THREAD

**Issue by PODAMEKALAPREETHI** [dhruvie/RSA#13]
getting error while generating def generateprimenumber

**Comment by dhruvie** [comment]
I have run the RSA.ipynb file. And it's running fine. Please try that file in google colab.

**Comment by PODAMEKALAPREETHI** [comment]
ok thank you

**Comment by PODAMEKALAPREETHI** [comment]
Is there any other app which runs fine for this code. (jupyter, spyder)

**Comment by PODAMEKALAPREETHI** [comment]
Did you install anything before running the code?
