### ISSUE TITLE
ValueError: assignment destination is read-only

### ISSUE THREAD

**Issue by PODAMEKALAPREETHI** [dhruvie/RSA#14]
while generating step 5:(Encryption)

**Comment by dhruvie** [comment]
May be the image you have taken is read-only and you are not allowed to change the value. Try using different image.

**Comment by PODAMEKALAPREETHI** [comment]
ok
I will try

**Comment by PODAMEKALAPREETHI** [comment]
Now I try to do with the same image which was used in this code. But still I am getting the same error

**Comment by PODAMEKALAPREETHI** [comment]
I got few errors like jpeg image has no object shape so i change it with size. Is there any chance because of this I'm getting error

**Comment by dhruvie** [comment]
If you have used  the same image that I have used, I don't know why you're getting this kind of error. Because in my system it's running totally fine.

**Comment by PODAMEKALAPREETHI** [comment]
Thank you so much issue got solved
