### ISSUE TITLE
error

### ISSUE THREAD

**Issue by roshnidash** [dhruvie/RSA#8]
Error: File: RSA.m Line: 2 Column: 1
The input character is not valid in MATLAB statements or expressions.
 

the above statement is the error shown in the program when it is executed

**Comment by dhruvie** [comment]
Run the RSA.ipynb file(in Google Colab) or RSA.py(if  open cv  is installed in your system).

**Comment by abhaspathak** [comment]
In Colab decryption image is not showing it show encrypted image
